### ISSUE TITLE
Database and API Instability

### ISSUE THREAD

**Issue by TheRealToxicDev** [TheRealToxicDev/InfinityBotsStatus#3]
We are aware of and actively looking into issues causing our API to throw a “to many redirects” error for some users using the `api.infinitybotlist.com` domain.

in the meantime if you are experiencing issues posting to or fetching stats from this domain please use our old domain Until further updates are posted: `api.infinitybots.xyz`

**Comment by TheRealToxicDev** [comment]
We are aware of and actively looking into issues causing our API to throw a “to many redirects” error for some users using the `api.infinitybotlist.com` domain.

in the meantime if you are experiencing issues posting to or fetching stats from this domain please use our old domain Until further updates are posted: `api.infinitybots.xyz`

**Comment by ChillCordDev** [comment]
# Update:
This issue has moved over to our main site as it seems our Database has become unresponsive, Maintenance mode has been activated for the entire site while our Dev Team works to resolve the issues. At the moment most services are unavailable

**Comment by TheRealToxicDev** [comment]
# Update:
• This downtime seems like it may be one that lasts a decent amount of time as we continue to struggle to fix the Database and API issues 

• The Infinity Bot Staff would to apologize in advance for any inconvenience this may cause and hope you will bare with us as we work out the issues ❤️

**Comment by Connor200024** [comment]
**Update:**

Hi all,

We are still aware of our Database and API being down.

We are sorry for any of the inconvenience that has been caused, our Development Team is doing everything they can to resolve this.

Kind Regards,

Head Developer - Connor200024

**Comment by MaximKing1** [comment]
# Update:
• We have identified the issue originated from our Database, we have spoken to our Database Manager and we are working on resolving the issue... We expect the issue to be solved tonight in the meantime why not enjoy this lovely Monday night ♥️

**Comment by TheRealToxicDev** [comment]
All services have been restored ❤️
