### ISSUE TITLE
Recent attacks on Infinitybotlist 

### ISSUE THREAD

**Issue by MaximKing1** [TheRealToxicDev/InfinityBotsStatus#4]
Dear Members,
We have detected a wide scale DDoS attack on our main site and API, we are in the progress on migrating our servers and the automated protection has kicked in and stopping the threats... All user and bot data is stored off site in a secure Database and the site remains unaffected for the time, we have noticed the attack growing bigger we have taken steps to prevent any damage and the Attackers IP has been blocked and reported to the relevant authorities.
For the meantime the site may be slower but we are closely monitoring this until the attacks stop.
Love From The IBL Team! :Love:

**Comment by ChillCordDev** [comment]
Our team will continue to monitor the attacks throughout the night and keep you all posted on any major downtime’s or changes ❤️

**Comment by TheRealToxicDev** [comment]
We are aware of and working on issues with the Website and CSS issues, Please be patient as we are moving servers :D

**Comment by TheRealToxicDev** [comment]
All issues have been resolved
